### ISSUE TITLE
Plugin error - java.lang.NullPointerException: null          

### ISSUE THREAD

**Issue by Crystal-Phoenix** [free-mc-plugins/AnimatedTeleport#2]
[23:40:04] [Server thread/INFO]: [AnimatedTeleport] Enabling AnimatedTeleport v1.6
[23:40:04] [Server thread/INFO]: [AnimatedTeleport] GTAStyleTeleport enabled
[23:40:04] [Server thread/ERROR]: Error occurred while enabling AnimatedTeleport v1.6 (Is it up to date?)
java.lang.NullPointerException: null
	at com.ericlam.main.AnimatedTeleport.reloadConfig(AnimatedTeleport.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:133) ~[patched_1.15.1.jar:git-Paper-33]
	at com.ericlam.main.AnimatedTeleport.onEnable(AnimatedTeleport.java:46) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-33]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-33]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-33]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-33]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-33]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[23:40:04] [Server thread/INFO]: [AnimatedTeleport] Disabling AnimatedTeleport v1.6
[23:40:04] [Server thread/INFO]: [AnimatedTeleport] GTAStyleTeleport disabled

**Comment by eric2788** [comment]
this plugin has already updated to version 2.4, please check the spigotmc
